### ISSUE TITLE
EMS Module - Donations to other ccat..add total donation

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#213]
1. create new custom attrs (via lock page) to record schemes to monitor..it would be a multi-select (scheme.findAllByStatusNull ..and show the scheme.cc.costCategory.name +":"+"scheme.name
2. in the correspoindg donations page, add a new column towards end to show total donations (for the chosen schemes only and for the current period...use Period domain to get the latest dates..if not present then default to current FY..

**Comment by slddrns** [comment]
Done but not tested thoroughly.
1. I have calculated the total only for each donor in the donation list which takes into consideration the locks, and not in the all donations list.
2. Line 5638 of Project controller, 
def uniqueDonatedBy = Donation.createCriteria().list() {
If I write 
def uniqueDonatedBy = result.createCriteria().list() {
then it gives the following error. I am not sure if the error is due to result being blank due to lack of data.
Message: No signature of method: grails.orm.PagedResultList.createCriteria() is applicable for argument types: () values: []
    Line | Method
->> 5638 | doCall    in ics.ProjectController$_closure48$$EQWu7cLh
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter  in     ''
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by slddrns** [comment]
I have made the total column for all donations now. 
But it is not tested.
