### ISSUE TITLE
Donation Module : Donation Record discrepancy checker

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#987]
For the NVCC_Admin role, have a link that will produce an output for the following query:

select * from donation d, donation_record dr where dr.receipt_received_status='NOTGENERATED' and dr.creator='gitconjivadm1' and d.nvcc_receipt_book_no=dr.rbno and d.nvcc_receipt_no=dr.rno

(creator has to be user input)

on page, https://server.konsoftech.in/ics/donationRecord/list

**Comment by susanta4** [comment]
implemented , page is not opening in my system. Before implementation same error was there
type Exception report

message Error applying layout : main

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : main
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:744)
root cause
